#!/bin/bash
#
# ifconfig was cool, and ip is more cool
# but most of the time, they are to verbose ;)


IFACES=`awk '{print $1}' < /proc/net/dev |grep ':' |cut -d ':' -f 1`

for iface in $IFACES ;do
    IP4_ADDR=`ip addr show dev $iface |grep -w inet |awk '{print $2}'`
    IP6_ADDR=`ip addr show dev $iface |grep -w inet6 |awk '{print $2}'`

    REPEAT_IFACE="$iface"

    if echo ${IP4_ADDR} |grep -q '.' ;then
        for addr in $IP4_ADDR ;do
            printf "%-15s %s\n" "$REPEAT_IFACE" "$addr" 
            REPEAT_IFACE= ;done ;fi

    if echo ${IP6_ADDR} |grep -q ':' ;then
        for addr in $IP6_ADDR ;do
            printf "%-15s %s\n" "$REPEAT_IFACE" "$addr" 
            REPEAT_IFACE= ;done ;fi

    echo ;done

