#!/bin/bash
#
# INFO:
#   set volume in alsamixer with pulse audio
#   for ubuntu 18.04
# 
# USAGE:
#   +       increase 5%
#   -       decrease 5%
#   0-100   set to value
#   m       mute / umnute

case $1 in
    + ) PARAM='5%+' ;;

    - ) PARAM='5%-' ;;

    m ) VOLUME=`awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master)`
        echo "VOLUME = $VOLUME"
        if [ "$VOLUME" != '0%' ] ;then
            echo "$VOLUME" > /tmp/volume.txt
            PARAM='0%' ;fi

        if [ "$VOLUME" = '0%' ] ;then
            if [ -f "/tmp/volume.txt" ] ;then
                PARAM=`cat /tmp/volume.txt`
            else
                PARAM='75%' ;fi ;fi ;;

    * ) if printf '%i' "${1}" &> /dev/zero ;then
            if [ "$1" -le 100 ] ;then
                PARAM="${1}%" ;fi ;fi ;;
esac

if [ -n "$PARAM" ] ;then
    amixer -D pulse set Master $PARAM ;fi
 
